name: Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      
      - name: Install dependencies
        run: go mod download
      - name: libz
        shell: bash
        run: sudo apt install -y libbz2-dev
      - name: Build
        run: go build -v -race ./...
      - name: Run vetting
        run: go vet
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.x'

    - name: Install dependencies
      run: go mod download

    - name: Test with the race detector
      run: go test -v -race ./...